# Generated by Django 5.2.13 on 2026-04-27 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0012_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsortiumMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_schools', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_teachers', models.PositiveIntegerField(default=0)),
                ('total_competitions_held', models.PositiveIntegerField(default=0)),
                ('total_exchanges_completed', models.PositiveIntegerField(default=0)),
                ('total_vendor_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_schools_this_month', models.PositiveIntegerField(default=0)),
                ('active_users_daily', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('teacher_count', models.PositiveIntegerField(default=0)),
                ('competition_registrations', models.PositiveIntegerField(default=0)),
                ('exchange_programs_participated', models.PositiveIntegerField(default=0)),
                ('content_views', models.PositiveIntegerField(default=0)),
                ('vendor_enquiries', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0, help_text='0-100 score based on activity')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tenants.school')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('school', 'date')},
            },
        ),
    ]
