# Generated by Django 5.2.13 on 2026-07-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Yarra Verification'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
