# Generated by Django 6.0.4 on 2026-04-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Current Review Cycle', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('self_study_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('self_study_start', models.DateField(blank=True, null=True)),
                ('self_study_end', models.DateField(blank=True, null=True)),
                ('self_study_document', models.FileField(blank=True, null=True, upload_to='review_documents/self_study/')),
                ('review_visit_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('review_visit_start', models.DateField(blank=True, null=True)),
                ('review_visit_end', models.DateField(blank=True, null=True)),
                ('review_visit_document', models.FileField(blank=True, null=True, upload_to='review_documents/review_visit/')),
                ('sip_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('sip_start', models.DateField(blank=True, null=True)),
                ('sip_end', models.DateField(blank=True, null=True)),
                ('sip_document', models.FileField(blank=True, null=True, upload_to='review_documents/sip/')),
                ('recommendations_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('recommendations_start', models.DateField(blank=True, null=True)),
                ('recommendations_end', models.DateField(blank=True, null=True)),
                ('recommendations_document', models.FileField(blank=True, null=True, upload_to='review_documents/recommendations/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cycles', to='tenants.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
