# Generated by Django 6.0.4 on 2026-04-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='tenants_not_recipie_d638ec_idx',
            old_name='tenants_not_recipie_ff0b31_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='tenants_not_recipie_231349_idx',
            old_name='tenants_not_recipie_1178c8_idx',
        ),
    ]
