# Generated by Django 6.0.4 on 2026-04-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_school_contact_person_school_key_offerings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherresource',
            name='capacity_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='capacity_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 1h 20m', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='presenter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='resource_type',
            field=models.CharField(choices=[('session', 'Upcoming PL Session'), ('recording', 'Past Recording'), ('document', 'Resource Document')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherresource',
            name='session_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherresource',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_hub/resources/'),
        ),
    ]
