# Generated by Django 6.0.4 on 2026-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_profile_aadhaar_no_profile_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='semester',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, help_text='e.g. Grade 10', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(blank=True, help_text='e.g. Section A', max_length=50),
        ),
    ]
