# Generated by Django 5.2.13 on 2026-04-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_school_is_active_school_membership_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='father_contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mother_contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='registration_no',
        ),
    ]
