# Generated by Django 5.2.13 on 2026-07-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_discussionthread_id_alter_invitation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='yarra_coordinator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='yarra_coordinator_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='yarra_coordinator_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('online', 'Online'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='online', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='school_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.school')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfileExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('association', models.CharField(blank=True, help_text='Association the school is a part of', max_length=200)),
                ('curriculum_adopted', models.CharField(blank=True, max_length=200)),
                ('grades_offered', models.CharField(blank=True, max_length=200)),
                ('total_learners', models.PositiveIntegerField(blank=True, null=True)),
                ('form_filled_by_name', models.CharField(blank=True, max_length=150)),
                ('form_filled_by_designation', models.CharField(blank=True, max_length=150)),
                ('form_filled_by_contact', models.CharField(blank=True, max_length=20)),
                ('parent_demographics', models.TextField(blank=True)),
                ('fee_structure', models.TextField(blank=True)),
                ('principal_name', models.CharField(blank=True, max_length=150)),
                ('principal_contact', models.CharField(blank=True, max_length=20)),
                ('communication_email', models.EmailField(blank=True, max_length=254)),
                ('curriculum_change_reason', models.TextField(blank=True)),
                ('vision_5_years', models.TextField(blank=True)),
                ('success_definition', models.TextField(blank=True)),
                ('curriculum_expectations', models.TextField(blank=True)),
                ('built_up_area', models.CharField(blank=True, max_length=100)),
                ('classroom_infrastructure', models.TextField(blank=True)),
                ('pd_programs_impact', models.TextField(blank=True)),
                ('immediate_support_needed', models.TextField(blank=True)),
                ('curriculum_planning_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tenants.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tenants_act_user_id_be7a2b_idx'), models.Index(fields=['school', '-created_at'], name='tenants_act_school__423f8c_idx')],
            },
        ),
    ]
