# Generated by Django 5.2.13 on 2026-07-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_school_country_school_facebook_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherResource',
        ),
    ]
