# Generated by Django 5.2.13 on 2026-08-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_delete_teacherresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aadhaar_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='alternate_mobile_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_curricular',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages_known',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='section',
        ),
    ]
