# Generated by Django 5.2.13 on 2026-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_remove_profile_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofileextended',
            name='achievements',
            field=models.TextField(blank=True, help_text='Achievements and highlights, one per line'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='leadership_team',
            field=models.TextField(blank=True, help_text="Leadership team, one 'Name — Title' per line"),
        ),
    ]
