# Generated by Django 5.2.13 on 2026-08-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_schoolprofileextended_achievements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='communication_email',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='curriculum_change_reason',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='curriculum_expectations',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='district',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='form_filled_by_contact',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='form_filled_by_designation',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='form_filled_by_name',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='success_definition',
        ),
        migrations.RemoveField(
            model_name='schoolprofileextended',
            name='total_learners',
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='assessment_practices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='curriculum_adopted_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='If Mixed/Other, please specify'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='fee_structure_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fee Structure (To)'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='fee_structure_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fee Structure (From)'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='focus_areas_2_5_years',
            field=models.TextField(blank=True, verbose_name='Focus for the next 2-5 years'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='grade_strength',
            field=models.JSONField(blank=True, default=dict, help_text='Number of students per grade, Toddler through Grade 12'),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='key_strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofileextended',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('school_leader', 'School Leader'), ('admin', 'Admin'), ('pl_teacher', 'PL Teacher'), ('teacher', 'Teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dnh_dd', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofileextended',
            name='curriculum_adopted',
            field=models.CharField(blank=True, choices=[('matric_state', 'Matric / State Board'), ('cbse', 'CBSE'), ('icse', 'ICSE'), ('cambridge', 'Cambridge'), ('ed_excel', 'Ed Excel'), ('ib', 'IB'), ('mixed', 'Mixed (specify)'), ('other', 'Other (specify)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolprofileextended',
            name='curriculum_planning_description',
            field=models.TextField(blank=True, help_text='Annual Curriculum Planning process (150-200 words)'),
        ),
        migrations.AlterField(
            model_name='schoolprofileextended',
            name='pd_programs_impact',
            field=models.TextField(blank=True, verbose_name='Professional Development Plan for Teachers'),
        ),
        migrations.AlterField(
            model_name='schoolprofileextended',
            name='vision_5_years',
            field=models.TextField(blank=True, verbose_name="School's Vision for Learning"),
        ),
        migrations.AlterField(
            model_name='schoolprofileextended',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Establishment'),
        ),
        migrations.CreateModel(
            name='EvaluatorQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('response_document', models.FileField(blank=True, null=True, upload_to='review_documents/evaluator_responses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_queries', to=settings.AUTH_USER_MODEL)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_queries', to='tenants.reviewcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YarraEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
