# Generated by Django 5.2.13 on 2026-08-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_remove_schoolprofileextended_communication_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('school_leader', 'School Leader'), ('admin', 'Admin'), ('teacher', 'Teacher')], max_length=20),
        ),
    ]
