# Generated by Django 5.2.13 on 2026-08-16 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfEvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluation', to='tenants.reviewcycle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfEvaluationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='review_documents/self_evaluation/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluation_files', to='tenants.reviewcycle')),
            ],
            options={
                'unique_together': {('review_cycle', 'question_id')},
            },
        ),
    ]
