# Generated by Django 5.2.13 on 2026-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_selfevaluationresponse_selfevaluationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofileextended',
            name='grade_strength',
            field=models.JSONField(blank=True, default=dict, help_text='Number of students per grade, Pre KG through Grade 12'),
        ),
    ]
