# Generated by Django 5.2.13 on 2026-08-16 10:17

from django.db import migrations, models


def clear_legacy_free_text(apps, schema_editor):
    """grades_offered was free text before this migration; blank it out to a
    JSON-safe empty string so the following AlterField (CharField -> JSONField)
    never tries to json.loads() an old free-text value like 'CBSE, Grade 1-10'."""
    SchoolProfileExtended = apps.get_model('tenants', 'SchoolProfileExtended')
    SchoolProfileExtended.objects.all().update(grades_offered='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_alter_schoolprofileextended_grade_strength'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_free_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='schoolprofileextended',
            name='grades_offered',
            field=models.JSONField(blank=True, default=list, help_text='Grade levels the school offers, Pre KG through Grade 12'),
        ),
    ]
