# Generated by Django 5.2.13 on 2026-04-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_school_is_active_school_membership_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('subject_grade', models.CharField(help_text='e.g. Mathematics - Grade 10', max_length=200)),
                ('duration', models.CharField(help_text='e.g. 1 week, 1 semester', max_length=100)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_listings', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why are you interested in this exchange?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_applications', to='tenants.school')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exchanges.exchangelisting')),
            ],
        ),
    ]
