# Generated by Django 5.2.13 on 2026-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_exchangemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapplication',
            name='applicant_school_feedback_comments',
            field=models.TextField(blank=True, help_text='Comments from applicant school'),
        ),
        migrations.AddField(
            model_name='exchangeapplication',
            name='applicant_school_feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from applicant school (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='exchangeapplication',
            name='listing_school_feedback_comments',
            field=models.TextField(blank=True, help_text='Comments from listing school'),
        ),
        migrations.AddField(
            model_name='exchangeapplication',
            name='listing_school_feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from listing school (1-5)', null=True),
        ),
    ]
