# Generated by Django 5.2.13 on 2026-07-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_exchangeapplication_applicant_school_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangelisting',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangelisting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
