# Generated by Django 5.2.13 on 2026-04-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('uniforms', 'Uniforms'), ('books_stationery', 'Books & Stationery'), ('edtech', 'EdTech'), ('furniture', 'Furniture & Fixtures'), ('transport', 'Transport'), ('canteen', 'Canteen Supplies'), ('sports', 'Sports Equipment'), ('lab', 'Lab Supplies'), ('infrastructure', 'Digital Infrastructure'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('consortium_offer', models.TextField(help_text='Special deal/discount for consortium members')),
                ('is_vetted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='vendor_promotions/')),
                ('offer_text', models.TextField()),
                ('cta_link', models.URLField()),
                ('placement', models.CharField(choices=[('homepage', 'Homepage Banner'), ('directory', 'Category Page Banner'), ('sidebar', 'Sidebar Spotlight')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='vendors.vendor')),
            ],
        ),
    ]
