# Generated by Django 5.2.13 on 2026-07-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorenquiry_status_eventinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='vendor_brochures/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='catalog',
            field=models.FileField(blank=True, null=True, upload_to='vendor_catalogs/'),
        ),
    ]
