# Generated by Django 6.0.4 on 2026-04-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='competitionresult',
            new_name='competition_school__caada7_idx',
            old_name='competition_school__6cb929_idx',
        ),
        migrations.RenameIndex(
            model_name='competitionresult',
            new_name='competition_event_i_51be61_idx',
            old_name='competition_event_i_57a516_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='competition_categor_4e796a_idx',
            old_name='competition_categor_ef7628_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='competition_school__cbc766_idx',
            old_name='competition_school__16ac24_idx',
        ),
        migrations.RenameIndex(
            model_name='studentregistration',
            new_name='competition_event_i_c589ec_idx',
            old_name='competition_event_i_7b8a97_idx',
        ),
        migrations.RenameIndex(
            model_name='studentregistration',
            new_name='competition_student_138fbe_idx',
            old_name='competition_student_9d613f_idx',
        ),
    ]
