# Generated by Django 6.0.4 on 2026-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_rename_competition_school__6cb929_idx_competition_school__caada7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('action', 'Yarra Action'), ('spotlight', 'Yarra Spotlight'), ('active', 'Yarra Active'), ('opportunity', 'Opportunity')], max_length=20),
        ),
    ]
