# Generated by Django 5.2.13 on 2026-04-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_event_capacity_event_event_date_event_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='feedback_rating',
            field=models.PositiveIntegerField(blank=True, help_text='1-5 rating', null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
    ]
