# Generated by Django 5.2.13 on 2026-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_studentregistration_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Registration fee for the event', max_digits=10),
        ),
    ]
