# Generated by Django 5.2.13 on 2026-07-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_event_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_type',
            field=models.CharField(choices=[('pro_bono', 'Pro Bono (Yarra Members)'), ('paid', 'Paid (Non Members)')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='presentation_file',
            field=models.FileField(blank=True, help_text='Presentation/slides from the event', null=True, upload_to='competitions/presentations/'),
        ),
        migrations.AddField(
            model_name='event',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Link to the event recording'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
