# Generated by Django 5.2.13 on 2026-07-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_event_fee_type_event_presentation_file_and_more'),
        ('tenants', '0014_school_country_school_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tenants.school'),
        ),
    ]
