# Generated by Django 5.2.13 on 2026-08-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_event_school'),
        ('tenants', '0018_remove_schoolprofileextended_communication_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='competitions/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='studentregistration',
            name='competition_student_138fbe_idx',
        ),
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='participant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='tenants.school'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['school', 'payment_status'], name='competition_school__b4ba9d_idx'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='competitions.event'),
        ),
    ]
