from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('school-profile/', views.school_profile, name='school_profile'),
    path('school-profile/<int:pk>/', views.school_profile, name='school_profile_detail'),
    path('master/', views.master_dashboard, name='master_dashboard'),
    path('school-review/', views.review_dashboard, name='review_dashboard'),
    path('school-review/create/', views.create_review_cycle, name='create_review_cycle'),
    path('school-review/self-evaluation/', views.self_evaluation_form, name='self_evaluation_form'),
    path('network/', views.school_network, name='school_network'),
    path('leadership/', views.leadership_connect, name='leadership_connect'),
    path('leadership/thread/<int:pk>/', views.thread_detail, name='thread_detail'),
    path('invite/', views.invite_user, name='invite_user'),
    path('invite/accept/<str:token>/', views.accept_invitation, name='accept_invitation'),
    path('register-school/', views.school_registration, name='school_registration'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/<int:pk>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('schools/new/', views.admin_create_school, name='admin_create_school'),
    path('schools/complete-profile/', views.complete_school_profile, name='complete_school_profile'),
    path('users/', views.user_management, name='user_management'),
    path('payments/record/', views.record_payment, name='record_payment'),
    path('payments/', views.payment_history, name='payment_history'),
    path('payments/<int:pk>/invoice/', views.download_payment_invoice, name='download_payment_invoice'),
    path('testing/switch-role/', views.switch_role, name='switch_role'),
    path('testing/return-to-admin/', views.return_to_admin, name='return_to_admin'),
    path('evaluator/', views.evaluator_dashboard, name='evaluator_dashboard'),
    path('evaluator/school/<int:school_pk>/', views.evaluator_review_detail, name='evaluator_review_detail'),
    path('evaluator/query/<int:pk>/answer/', views.evaluator_answer_query, name='evaluator_answer_query'),
]
